# Generated by Django 4.2.2 on 2023-06-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.PositiveIntegerField(blank=True, null=True)),
                ('expedito', models.CharField(blank=True, choices=[('Lp', 'La Paz'), ('Or', 'Oruro'), ('Pt', 'Potosi'), ('Cbba', 'Cochabamba'), ('Ch', 'Chuquisaca'), ('Tj', 'Tarija'), ('Sc', 'Santa Cruz'), ('Bn', 'Beni'), ('Pn', 'Pando')], max_length=10, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('celular', models.PositiveIntegerField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socio',
                'managed': True,
            },
        ),
    ]
