# Generated by Django 4.2.2 on 2023-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
