# Generated by Django 4.2.2 on 2023-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocio', '0002_alter_socio_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellidos Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ci',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cedula de Identidad'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='codigo',
            field=models.CharField(max_length=8, unique=True, verbose_name='Codigo Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion del Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activar'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono Fijo'),
        ),
    ]
