# Generated by Django 4.2.2 on 2023-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocio', '0003_alter_socio_apellido_alter_socio_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='expedito',
            field=models.CharField(blank=True, choices=[('La Paz', 'Lp'), ('Oruro', 'Or'), ('Potosi', 'Pt'), ('Cochabamba', 'Cbba'), ('Chuquisaca', 'Ch'), ('Tarija', 'Tj'), ('Santa Cruz', 'Sc'), ('Beni', 'Bn'), ('Pando', 'Pn')], max_length=10, null=True),
        ),
    ]
