# Generated by Django 4.2.4 on 2023-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsocio', '0004_alter_socio_expedito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ci',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='expedito',
            field=models.CharField(blank=True, choices=[('Lp', 'Lp'), ('Or', 'Or'), ('Pt', 'Pt'), ('Cbba', 'Cbba'), ('Ch', 'Ch'), ('Tj', 'Tj'), ('Sc', 'Sc'), ('Bn', 'Bn'), ('Pn', 'Pn')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
