# Generated by Django 4.2.2 on 2023-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applectura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='actual',
            field=models.FloatField(verbose_name='Lectura Actual'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='anio',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='Gestion'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='anterior',
            field=models.FloatField(verbose_name='Lectura Anterior'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='consumo',
            field=models.FloatField(verbose_name='Consumo en m3'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='estado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='mes',
            field=models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=10, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='multa',
            field=models.FloatField(verbose_name='Multa Varios'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='pagoconsumo',
            field=models.FloatField(verbose_name='Monto de Consumo'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='pagototal',
            field=models.FloatField(verbose_name='Monto total a pagar'),
        ),
    ]
