# Generated by Django 4.2.2 on 2023-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applectura', '0002_alter_lectura_actual_alter_lectura_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='anio',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4, verbose_name='Gestion'),
        ),
    ]
