# Generated by Django 4.2.2 on 2023-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applectura', '0003_alter_lectura_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emision'),
        ),
    ]
