# Generated by Django 4.2.4 on 2023-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applectura', '0004_lectura_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='fecha',
            new_name='fechaemision',
        ),
        migrations.AddField(
            model_name='lectura',
            name='fechapago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
