# Generated by Django 4.2.4 on 2023-08-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applectura', '0005_rename_fecha_lectura_fechaemision_lectura_fechapago'),
        ('appcobrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrar',
            name='lectura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='applectura.lectura'),
        ),
    ]
