# Generated by Django 4.2.2 on 2023-06-19 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptroncal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georeferencias',
            name='multilinea',
        ),
        migrations.AlterField(
            model_name='georeferencias',
            name='linea',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='georeferencias',
            name='multipoligono',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='georeferencias',
            name='multipunto',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='georeferencias',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='georeferencias',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
