# Generated by Django 4.2.2 on 2023-06-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptroncal', '0002_remove_georeferencias_multilinea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georeferencias',
            name='linea',
        ),
    ]
